### ISSUE TITLE
ImportError: No module named 'snippets'

### ISSUE THREAD

**Issue by benfairless** [Skablam/flask-spawn#1]
It seems that the shell command spawn is having difficulty finding the path to the 'snippets' module inside Flask-Spawn

Steps to reproduce:
- Create a new virtual environment
- Install Flask-Spawn via PIP
- Run `spawn` shell command

Error message:

```
$ spawn
Traceback (most recent call last):
  File "/tmp/flask-spawn/bin/spawn", line 9, in <module>
    load_entry_point('flask-spawn==0.1.3', 'console_scripts', 'spawn')()
  File "/tmp/flask-spawn/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/flask-spawn/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/tmp/flask-spawn/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/tmp/flask-spawn/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/flask-spawn/lib64/python3.4/site-packages/flaskspawn/spawn.py", line 2, in <module>
    from snippets.snippets import add_database_files
ImportError: No module named 'snippets'
```

PIP install:

```
$ pip install flask-spawn
Collecting flask-spawn
  Using cached flask-spawn-0.1.3.tar.gz
Collecting Click==3.3 (from flask-spawn)
  Using cached click-3.3-py2.py3-none-any.whl
Collecting Cookiecutter (from flask-spawn)
  Using cached cookiecutter-1.0.0-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from Cookiecutter->flask-spawn)
  Using cached PyYAML-3.11.tar.gz
Collecting jinja2>=2.7 (from Cookiecutter->flask-spawn)
  Using cached Jinja2-2.7.3.tar.gz
Collecting binaryornot>=0.2.0 (from Cookiecutter->flask-spawn)
  Using cached binaryornot-0.3.0.tar.gz
Collecting mock (from Cookiecutter->flask-spawn)
  Using cached mock-1.0.1.tar.gz
Collecting markupsafe (from jinja2>=2.7->Cookiecutter->flask-spawn)
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: markupsafe, mock, binaryornot, jinja2, PyYAML, Cookiecutter, Click, flask-spawn
  Running setup.py install for markupsafe
  Running setup.py install for mock
  Running setup.py install for binaryornot
  Running setup.py install for jinja2
  Running setup.py install for PyYAML
  Running setup.py install for flask-spawn
    Installing spawn script to /tmp/flask-spawn/bin
Successfully installed Click-3.3 Cookiecutter-1.0.0 PyYAML-3.11 binaryornot-0.3.0 flask-spawn-0.1.3 jinja2-2.7.3 markupsafe-0.23 mock-1.0.1
```

**Comment by benfairless** [comment]
If I move the snippets module into it's own directory in 'site-packages' I get the expected behaviour.
`mv lib/python3.4/site-packages/flaskspawn/snippets lib/python3.4/site-packages/`

```
$ spawn
Usage: spawn [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  new
```

**Comment by Skablam** [comment]
Changed imports to be python 3 friendly. Can you try version version 0.1.4 and see if that has sorted it?

**Comment by benfairless** [comment]
Yep. This fixes it :+1:
